Add developer profile validation
CodersCrew/CodersCard pull request #110
Opened 2020-10-27 16:20 UTC by celinawierzbicka

2020-10-27 17:38 UTC, mecies requested changes
One small change, other than that looks good to me 😄 

I don't understand the URL regex at all, but I tested it in the browser and it worked for URLs and refused not URLs

2020-10-27 17:38 UTC, mecies commented on static/admin/config.yml
> +      - { label: "Email", name: "email", widget: "string", pattern: ['/^.+@.+\..+$/', "Must be a valid e=mail address"] }
```suggestion
      - { label: "Email", name: "email", widget: "string", pattern: ['/^.+@.+\..+$/', "Must be a valid email address"] }
```
this character is unnecessary 😄

2020-10-27 21:08 UTC, celinawierzbicka commented on static/admin/config.yml
> +      - { label: "Email", name: "email", widget: "string", pattern: ['/^.+@.+\..+$/', "Must be a valid e=mail address"] }
ooohh... fixed now :)

2020-10-28 20:23 UTC, mecies approved these changes
Good job, ready to merge ✅

2020-10-29 06:50 UTC, merged