Prevent scrollbar from changing page width
CodersCrew/CodersCard pull request #136
Opened 2020-11-12 14:07 UTC by KlaraGajaszek

Closes #134

2020-11-12 18:18 UTC, mecies approved these changes
Looks good to me 👍  ✅

2020-11-12 19:42 UTC, celinawierzbicka approved these changes

2020-11-12 21:25 UTC, KonradSzwarc approved these changes

2020-11-12 21:25 UTC, KonradSzwarc commented on src/components/Layout/Layout.tsx
> +  const html = document.querySelector('html') as HTMLElement;
Isn't it possible to set global CSS styles in Gatsby?

2020-11-12 21:27 UTC, KonradSzwarc requested changes

2020-11-12 21:27 UTC, KonradSzwarc commented on src/components/Layout/Layout.tsx
> +  const html = document.querySelector('html') as HTMLElement;
Isn't it possible to set global CSS styles in Gatsby?

2020-11-15 14:20 UTC, KonradSzwarc approved these changes

2020-11-15 21:26 UTC, merged