Add other tab to projects filter tabs
CodersCrew/CodersCard pull request #151
Opened 2020-11-19 22:28 UTC by KlaraGajaszek

closed #133

2020-11-20 21:06 UTC, mecies requested changes
Nice job Klara 💪 

The thingy is working nicely, we just need to get rid of one heavy guy 🗿

2020-11-20 21:06 UTC, mecies commented on package.json
> +    "lodash": "^4.17.20",
Please do not add `lodash` to the project, we don't need a heavy library, we only need one simple function 🎉

2020-11-20 21:06 UTC, mecies commented on src/pages/portfolio/index.tsx
> +};
in `/views/portfolio-page` create `utils.ts` file and move the helper function there

2020-11-20 21:06 UTC, mecies commented on src/pages/portfolio/index.tsx
> +
also move to `/views/portfolio-page/utils.ts`

2020-11-20 21:06 UTC, mecies commented on src/pages/portfolio/index.tsx
> +    .flat(1);
Please notice that this implementation breaks switching between projects while looking at `PortfolioProjectDialog` view,  please consider refactoring this function or refactoring `handleCloseProject`, `handlePreviousProject` and `handleNextProject` not to rely on indices, wdyt? 😄

2020-11-20 21:06 UTC, mecies commented on src/pages/portfolio/index.tsx
> +  const groupedProjects: Record<string, ProjectType[]> = _.groupBy(projects, 'projectLabel');
We could add `lodash` if it was useful application-wide, for a single-use case you don't need a whole library.
Moreover, in my opinion, you don't need a generic function for only handling project labels.

Let's define our own groupByProjectLabel and move it to `/views/portfolio-page/utils.ts`

If you want you can try this, it should work 😄 
I took a generic groupBy method and transformed it to our use-case, lodash bundle size is sooo huge 🍭 
```typescript
function groupByProjectLabel(projects: ProjectType[]): Record<string, ProjectType[]> {
  return projects.reduce((groupedProjects, project) => {
    // eslint-disable-next-line no-param-reassign
    (groupedProjects[project.projectLabel] = groupedProjects[project.projectLabel] || []).push(project);
    return groupedProjects;
  }, {} as { [key: string]: ProjectType[] });
}
```

2020-11-20 21:06 UTC, mecies commented on src/pages/portfolio/index.tsx
> +import * as _ from 'lodash';
This guy has to go 🚀

2020-11-20 23:27 UTC, KonradSzwarc requested changes

2020-11-20 23:27 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +const OtherLabel = 'More';
Why is it written in CamelCase?

2020-11-20 23:27 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +const numberOfMaxTabs = 3;
Maybe `maxNumberOfTabs` would be better

2020-11-20 23:27 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +  const defaultNavbarTitle = 'All';
It's constant so you can move it outside of the component

2020-11-20 23:27 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +    const title: Record<number, string> = { ...projectsLabels };
Why do you need to convert the array to an object here?

2020-11-24 16:48 UTC, KonradSzwarc requested changes

2020-11-24 16:48 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +  // choose next project or if is last label, choose first label
In my opinion, the name of the function is really meaningful and we don't need a comment here

2020-11-24 16:48 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +  // choose previous project or if is first label, choose last label
In my opinion, the name of the function is really meaningful and we don't need a comment here

2020-11-24 16:48 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +  const filteredProjects = sortedGroupsOfProjects
Maybe just name the variable `projesctFilteredByLabel` and remove the comment above

2020-11-24 16:48 UTC, KonradSzwarc commented on src/pages/portfolio/index.tsx
> +    const title = projectsLabels;
Why do you need to assign `projectsLabels` to a variable here?

2020-11-24 16:48 UTC, KonradSzwarc commented on src/pages/portfolio/utils.ts
> +  }, {} as { [key: string]: ProjectType[] });
Wouldn't it work if you write `reduce<{ [key: string]: ProjectType[] }>(...)` instead of this type casting?

2020-11-24 17:23 UTC, mecies requested changes
Agree with @KonradSzwarc  suggestions, please also move `src/pages/portfolio/utils.ts` to => `/src/views/portfolio-page/utils.ts`
Only page components can be stored in the `/pages` directory because Gatsby creates routes out of them automatically, util file in pages directory will break the production build 😄

2020-11-24 18:07 UTC, mecies commented on src/views/portfolio-page/utils.ts
> +const groupBy = (projects: ProjectType[]) => {
I suggest to name it `groupByProjectLabel` because it has `projectLabel` hardcoded in the function 😄

2020-11-24 18:50 UTC, mecies approved these changes
Good job 🚀 
Looks good to me ✅

2020-11-25 19:08 UTC, KonradSzwarc approved these changes

2020-11-25 19:09 UTC, merged