Create TextField component
CodersCrew/CodersCard pull request #35
Opened 2020-07-18 23:21 UTC by KlaraGajaszek

Closes #15

2020-07-19 19:02 UTC, KonradSzwarc requested changes

2020-07-19 19:02 UTC, KonradSzwarc commented on src/components/TextField/TextField.stories.tsx
> +  return <TextField InputProps={{ disableUnderline: true }} {...basePropsData} />;
As we always have to pass the `{ disableUnderline: true }` set it as a default prop in the component file.

2020-07-19 19:02 UTC, KonradSzwarc commented on src/components/TextField/TextField.stories.tsx
> +  return <TextField InputProps={{ disableUnderline: true, multiline: true }} {...basePropsData} />;
Can you pass `miltiline` prop directly to the `TextField` component (without `InputProps `)?

2020-07-19 19:02 UTC, KonradSzwarc commented on src/components/TextField/TextField.tsx
> +  TextField: {
Use camelCase for object properties

2020-07-19 19:02 UTC, KonradSzwarc commented on src/components/TextField/TextField.tsx
> +      fontSize: '16px',
It's `body1` font from the theme. My fault - I didn't describe it in Zeplin

2020-07-21 15:16 UTC, KonradSzwarc commented on src/components/TextField/TextField.stories.tsx
> +  return <TextField multiline={true} {...basePropsData} />;
It could be just `<TextField multiline {...basePropsData} />`

2020-07-21 15:18 UTC, KonradSzwarc commented on .github/workflows/chromatic.yml
> -name: "Chromatic Deployment"
Why you deleted this file?

2020-07-21 15:20 UTC, KonradSzwarc requested changes

2020-07-21 15:20 UTC, KonradSzwarc commented on .github/workflows/chromatic.yml
> -name: "Chromatic Deployment"
Why did you delete this file?

2020-07-21 15:20 UTC, KonradSzwarc commented on src/components/TextField/TextField.stories.tsx
> +  return <TextField multiline={true} {...basePropsData} />;
It could be just `<TextField multiline {...basePropsData} />`

2020-07-21 16:35 UTC, KlaraGajaszek commented on .github/workflows/chromatic.yml
> -name: "Chromatic Deployment"
My mistake

2020-07-25 12:18 UTC, KonradSzwarc approved these changes

2020-07-25 12:18 UTC, merged