Create FilterTabs and FilterTab components
CodersCrew/CodersCard pull request #57
Opened 2020-08-04 17:29 UTC by kacperjanusz

2020-08-05 20:37 UTC, KlaraGajaszek requested changes

2020-08-05 20:37 UTC, KlaraGajaszek commented on src/components/FilterTab/FilterTab.tsx
> +      color: theme.palette,
We should add sth more theme.palette...

2020-08-05 20:37 UTC, KlaraGajaszek commented on src/components/Button/Button.stories.tsx
>  import React from 'react';
Button component should be merged as a separate PR

2020-08-05 20:37 UTC, KlaraGajaszek commented on src/components/FilterTab/FilterTab.tsx
> +  Tab: {
Maybe lowercase => tab

2020-08-05 20:37 UTC, KlaraGajaszek commented on src/components/FilterTabs/FilterTabs.tsx
> +const useStyles = makeStyles((theme) => ({
I think you don't need it

2020-08-05 20:37 UTC, KlaraGajaszek commented on src/components/FilterTabs/FilterTabs.stories.tsx
> +export default {
I think, you should add component: FilterTabs

2020-08-11 15:49 UTC, KonradSzwarc requested changes

2020-08-11 15:49 UTC, KonradSzwarc commented on src/components/FilterTabs/FilterTabs.tsx
> +  const handleChange = (event: React.ChangeEvent<{}>, newValue: number) => {
Use type from the library.
`const handleChange: MuiTabsProps ['onChange']` = (event, newValue) => {

2020-08-11 15:49 UTC, KonradSzwarc commented on src/components/FilterTabs/FilterTabs.tsx
> +export type TabsProps = MuiTabsProps;
Add a new line between imports and types

2020-08-11 15:49 UTC, KonradSzwarc commented on src/components/FilterTab/FilterTab.tsx
> +export const FilterTab = (props: TabProps): JSX.Element => {
You don't need to specify return type explicitly

2020-08-26 17:12 UTC, KlaraGajaszek approved these changes

2020-08-28 15:25 UTC, KonradSzwarc approved these changes

2020-09-01 12:09 UTC, merged