Create BlogPostDialog component
CodersCrew/CodersCard pull request #58
Opened 2020-08-06 09:49 UTC by KlaraGajaszek

Closing #51

2020-08-06 18:43 UTC, maciekkwiet requested changes

2020-08-06 18:43 UTC, maciekkwiet commented on src/components/BlogPost/BlogPostDialog.stories.tsx
> +};
I think that isOpen should be set permanently isOpen={true}

2020-08-06 18:43 UTC, maciekkwiet commented on src/components/BlogPost/BlogPostDialog.tsx
> +export const BlogPostDialog: FC<BlogPostDialogProps & DetailsBlogPostDialogType> = ({ isOpen, type, ...props }) => {
BlogPostDialogType is unnecessary
DetailsBlogPostDialogType can be extended(&) BlogPostDialogProps by type: 'mobile' | 'tablet' | 'desktop';  This type doesn't need to be exported
Now we can write: FC<DetailsBlogPostDialogType>

2020-08-06 18:43 UTC, maciekkwiet commented on src/components/BlogPost/BlogPostDialogMobile.tsx
> +    height: 180,
If we set height: 180, we need to set width: 'auto' 
But maybe better idea is to set width: "100%" and height: "auto"

2020-08-08 16:27 UTC, celinawierzbicka approved these changes

2020-08-16 21:32 UTC, maciekkwiet approved these changes

2020-08-29 12:47 UTC, maciekkwiet approved these changes

2020-08-29 16:17 UTC, merged